name: 'Convert to GeoJSON'
description: 'Converts Excel files or CSV to GeoJSON'
author: 'Geolonia'
branding:
  icon: 'file-text'
  color: 'orange'
inputs:
  input_dir:
    description: 'Input directory where Excel files are placed'
    required: true
    default: './'
runs:
  using: 'node16'
  main: 'dist/index.js'
